services:

  mysql93:
    image: docker.io/bitnami/mysql:9.3
    ports:
      - '3306:3306'
    volumes:
      - 'mysql93_data:/bitnami/mysql/data'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis80:
    image: docker.io/bitnami/redis:8.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis80_data:/bitnami/redis/data'

  elasticsearch9:
    image: docker.io/bitnami/elasticsearch:9
    environment:
      - ELASTICSEARCH_PASSWORD=elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch9_data:/bitnami/elasticsearch/data'

  rabbitmq41:
    image: docker.io/bitnami/rabbitmq:4.1
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_USERNAME=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      - 'rabbitmq41_data:/bitnami/rabbitmq/mnesia'

  zookeeper39:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper39_data:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka40:
    image: docker.io/bitnami/kafka:4.0
    ports:
      - "9092:9092"
    volumes:
      - "kafka40_data:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka40:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

volumes:
  mysql93_data:
    driver: local
  redis80_data:
    driver: local
  elasticsearch9_data:
    driver: local
  rabbitmq41_data:
    driver: local
  zookeeper39_data:
    driver: local
  kafka40_data:
    driver: local
